#!/usr/bin/env python3
"""repo-audit.py — scheduled, unattended audit that files findings as issues.

    python3 scripts/repo-audit.py [--repo OWNER/REPO ...] [--dry-run]
                                  [--model SELECTOR] [--max-issues N]
                                  [--timeout SECONDS]

For each repository in repo-audit/repos.txt (or each --repo), keeps a private
clone under $XDG_CACHE_HOME/repo-audit/, resets it to the default branch, and
runs one headless `omp -p` session with repo-audit/prompt.md. The session
writes its findings as JSON; this script validates them, drops any whose key
an existing issue already carries (open or closed), caps the rest, and files
each as an issue labelled `needs-triage` and `enhancement`. The model never
writes to GitHub itself.

--dry-run prints the issues instead of filing them. Exit status is 1 when any
repository failed, so the systemd unit's OnFailure= alert fires; the other
repositories are still audited.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPOS_FILE = ROOT / "repo-audit" / "repos.txt"
PROMPT_FILE = ROOT / "repo-audit" / "prompt.md"

DEFAULT_MODEL = "anthropic/claude-sonnet-5-5:high"
DEFAULT_MAX = 5
DEFAULT_TIMEOUT = 3600
LABELS = ("needs-triage", "enhancement")
DISCLAIMER = "> *This was generated by AI during a scheduled repo audit.*"

KEY_RE = re.compile(r"^[a-z0-9][a-z0-9-]{2,59}$")
MARKER_RE = re.compile(r"<!-- repo-audit:([a-z0-9-]+) -->")
KINDS = {"architecture", "drift", "reference", "stale", "check"}
STRENGTHS = {"Strong", "Worth exploring", "Speculative"}


class AuditError(Exception):
    pass


def read_repos(path: Path) -> list[str]:
    repos = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            repos.append(line)
    return repos


def parse_findings(text: str) -> list[dict]:
    """Validate the session's JSON. Any malformed finding fails the repo:
    filing a half-understood finding is worse than filing none."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise AuditError(f"findings file is not JSON: {e}") from e
    findings = data.get("findings") if isinstance(data, dict) else None
    if not isinstance(findings, list):
        raise AuditError("findings file has no `findings` list")
    seen = set()
    for i, f in enumerate(findings):
        where = f"finding {i + 1}"
        if not isinstance(f, dict):
            raise AuditError(f"{where} is not an object")
        for field in ("key", "kind", "strength", "title", "body"):
            if not isinstance(f.get(field), str) or not f[field].strip():
                raise AuditError(f"{where} lacks a `{field}` string")
        if not KEY_RE.match(f["key"]):
            raise AuditError(f"{where} key {f['key']!r} is not a 3-60 char kebab slug")
        if f["key"] in seen:
            raise AuditError(f"{where} repeats key {f['key']!r}")
        seen.add(f["key"])
        if f["kind"] not in KINDS:
            raise AuditError(f"{where} kind {f['kind']!r} is not one of {sorted(KINDS)}")
        if f["strength"] not in STRENGTHS:
            raise AuditError(f"{where} strength {f['strength']!r} is not one of {sorted(STRENGTHS)}")
        if len(f["title"]) > 120:
            raise AuditError(f"{where} title is over 120 characters")
    return findings


def existing_keys(issue_bodies: list[str]) -> set[str]:
    keys = set()
    for body in issue_bodies:
        keys.update(MARKER_RE.findall(body or ""))
    return keys


def select(findings: list[dict], known: set[str], limit: int) -> list[dict]:
    """Drop findings an issue already tracks (any state, so a closed or
    rejected finding is never re-filed), then keep the first `limit`."""
    return [f for f in findings if f["key"] not in known][:limit]


def render_body(finding: dict) -> str:
    return (
        f"{DISCLAIMER}\n\n"
        f"**Kind:** {finding['kind']} · **Strength:** {finding['strength']}\n\n"
        f"{finding['body'].strip()}\n\n"
        f"<!-- repo-audit:{finding['key']} -->\n"
    )


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, text=True, capture_output=True, **kw)


def sync_clone(repo: str, cache: Path) -> Path:
    clone = cache / repo.replace("/", "-")
    if not (clone / ".git").is_dir():
        clone.parent.mkdir(parents=True, exist_ok=True)
        run(["gh", "repo", "clone", repo, str(clone), "--", "--quiet"])
    run(["git", "-C", str(clone), "fetch", "--quiet", "--prune", "origin"])
    run(["git", "-C", str(clone), "remote", "set-head", "origin", "--auto"])
    run(["git", "-C", str(clone), "reset", "--quiet", "--hard", "origin/HEAD"])
    run(["git", "-C", str(clone), "clean", "-ffdxq"])
    return clone


def audit_repo(repo: str, args, cache: Path, state: Path) -> int:
    clone = sync_clone(repo, cache)
    stamp = dt.datetime.now().strftime("%Y-%m-%dT%H%M")
    name = repo.replace("/", "-")
    out = state / f"{name}-{stamp}.json"
    log = state / f"{name}-{stamp}.log"
    prompt = (
        PROMPT_FILE.read_text()
        .replace("{{REPO}}", repo)
        .replace("{{OUT}}", str(out))
        .replace("{{MAX}}", str(args.max_issues))
    )
    with log.open("w") as fh:
        try:
            subprocess.run(
                ["omp", "-p", "--model", args.model, prompt],
                cwd=clone, stdin=subprocess.DEVNULL, stdout=fh, stderr=subprocess.STDOUT,
                timeout=args.timeout, check=True,
            )
        except subprocess.TimeoutExpired as e:
            raise AuditError(f"omp session exceeded {args.timeout}s (log: {log})") from e
        except subprocess.CalledProcessError as e:
            raise AuditError(f"omp exited {e.returncode} (log: {log})") from e
    if not out.is_file():
        raise AuditError(f"session wrote no findings file (log: {log})")
    findings = parse_findings(out.read_text())

    listed = run(["gh", "issue", "list", "--repo", repo, "--state", "all",
                  "--limit", "1000", "--json", "body"])
    known = existing_keys([i["body"] for i in json.loads(listed.stdout)])
    chosen = select(findings, known, args.max_issues)
    skipped = len(findings) - len(chosen)
    print(f"{repo}: {len(findings)} findings, {len(chosen)} new, {skipped} already tracked or over the cap")

    for f in chosen:
        body = render_body(f)
        if args.dry_run:
            print(f"\n--- [dry run] {repo}: {f['title']}\n{body}")
            continue
        cmd = ["gh", "issue", "create", "--repo", repo, "--title", f["title"], "--body", body]
        for label in LABELS:
            cmd += ["--label", label]
        print("  " + run(cmd).stdout.strip())
    return len(chosen)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--repo", action="append", help="audit only this OWNER/REPO (repeatable)")
    p.add_argument("--dry-run", action="store_true", help="print issues instead of filing them")
    p.add_argument("--model", default=DEFAULT_MODEL)
    p.add_argument("--max-issues", type=int, default=DEFAULT_MAX)
    p.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT, help="seconds per repo session")
    args = p.parse_args(argv)

    home = Path.home()
    cache = Path(os.environ.get("XDG_CACHE_HOME", home / ".cache")) / "repo-audit"
    state = Path(os.environ.get("XDG_STATE_HOME", home / ".local" / "state")) / "repo-audit"
    state.mkdir(parents=True, exist_ok=True)

    failed = []
    for repo in args.repo or read_repos(REPOS_FILE):
        try:
            audit_repo(repo, args, cache, state)
        except (AuditError, subprocess.CalledProcessError) as e:
            detail = e.stderr.strip() if isinstance(e, subprocess.CalledProcessError) and e.stderr else e
            print(f"{repo}: FAILED: {detail}", file=sys.stderr)
            failed.append(repo)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
